import { MigrationInterface, QueryRunner } from "typeorm";

export class Migration202505252001061748203268261 implements MigrationInterface {
    name = 'Migration202505252001061748203268261'

    public async up(queryRunner: QueryRunner): Promise<void> {
        await queryRunner.query(`CREATE TABLE "tiktok_order_items" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "shop_id" character varying NOT NULL, "order_id" character varying NOT NULL, "line_item_id" character varying NOT NULL, "currency" character varying, "display_status" character varying, "is_gift" boolean NOT NULL DEFAULT false, "original_price" numeric(10,2), "package_id" character varying, "package_status" character varying, "platform_discount" numeric(10,2), "product_id" character varying, "product_name" character varying, "rts_time" TIMESTAMP, "sale_price" numeric(10,2), "seller_discount" numeric(10,2), "seller_sku" character varying, "shipping_provider_id" character varying, "shipping_provider_name" character varying, "sku_id" character varying, "sku_image" text, "sku_name" character varying, "sku_type" character varying, "tracking_number" character varying, "created_at" TIMESTAMP NOT NULL DEFAULT now(), "updated_at" TIMESTAMP NOT NULL DEFAULT now(), CONSTRAINT "PK_92b4ab913ece0d503b19e8438f5" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE UNIQUE INDEX "IDX_a4672a3f9103944d50c78d5bb6" ON "tiktok_order_items" ("shop_id", "order_id", "line_item_id") `);
        await queryRunner.query(`CREATE TABLE "tiktok_orders" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "order_id" character varying NOT NULL, "shop_id" character varying NOT NULL, "buyer_email" character varying, "buyer_message" text, "cancel_order_sla_time" TIMESTAMP, "collection_due_time" TIMESTAMP, "collection_time" TIMESTAMP, "commerce_platform" character varying, "create_time" TIMESTAMP, "delivery_option_id" character varying, "delivery_option_name" character varying, "delivery_time" TIMESTAMP, "delivery_type" character varying, "fulfillment_type" character varying, "has_updated_recipient_address" boolean NOT NULL DEFAULT false, "tiktok_id" character varying, "is_cod" boolean NOT NULL DEFAULT false, "is_on_hold_order" boolean NOT NULL DEFAULT false, "is_replacement_order" boolean NOT NULL DEFAULT false, "is_sample_order" boolean NOT NULL DEFAULT false, "currency" character varying, "original_shipping_fee" numeric(10,2), "original_total_product_price" numeric(10,2), "platform_discount" numeric(10,2), "seller_discount" numeric(10,2), "shipping_fee" numeric(10,2), "shipping_fee_cofunded_discount" numeric(10,2), "shipping_fee_platform_discount" numeric(10,2), "shipping_fee_seller_discount" numeric(10,2), "sub_total" numeric(10,2), "tax" numeric(10,2), "total_amount" numeric(10,2), "payment_method_name" character varying, "address_detail" text, "country" character varying, "region" character varying, "province" character varying, "municipality" character varying, "barangay" character varying, "first_name" character varying, "first_name_local_script" character varying, "full_address" text, "last_name" character varying, "last_name_local_script" character varying, "name" character varying, "phone_number" character varying, "postal_code" character varying, "region_code" character varying, "rts_sla_time" TIMESTAMP, "rts_time" TIMESTAMP, "shipping_due_time" TIMESTAMP, "shipping_provider" character varying, "shipping_provider_id" character varying, "shipping_type" character varying, "status" character varying, "tracking_number" character varying, "tts_sla_time" TIMESTAMP, "update_time" TIMESTAMP, "user_id" character varying, "warehouse_id" character varying, "packages_id" character varying, "created_at" TIMESTAMP NOT NULL DEFAULT now(), "updated_at" TIMESTAMP NOT NULL DEFAULT now(), CONSTRAINT "PK_85c8c472a291cc073e4b7e390b9" PRIMARY KEY ("id", "order_id", "shop_id"))`);
        await queryRunner.query(`CREATE UNIQUE INDEX "IDX_2cfaf74396d1b42c769b0e2a6b" ON "tiktok_orders" ("shop_id", "order_id") `);
        await queryRunner.query(`ALTER TABLE "tiktok_order_items" ADD CONSTRAINT "FK_819f4fe414cfce96fb1e9c18a9d" FOREIGN KEY ("shop_id", "order_id") REFERENCES "tiktok_orders"("shop_id","order_id") ON DELETE CASCADE ON UPDATE NO ACTION`);
    }

    public async down(queryRunner: QueryRunner): Promise<void> {
        await queryRunner.query(`ALTER TABLE "tiktok_order_items" DROP CONSTRAINT "FK_819f4fe414cfce96fb1e9c18a9d"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_2cfaf74396d1b42c769b0e2a6b"`);
        await queryRunner.query(`DROP TABLE "tiktok_orders"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_a4672a3f9103944d50c78d5bb6"`);
        await queryRunner.query(`DROP TABLE "tiktok_order_items"`);
    }

}
